#!/usr/bin/env python3
"""Emit plain-English Mermaid: grey containment, colored connection arrows."""

from __future__ import annotations

import json
from pathlib import Path

CAD = Path(__file__).resolve().parent
ASM = CAD / "assembly.json"
OUT = CAD / "assembly_hierarchy.mmd"

# Grey = "is inside / contains". Teal = "mates at a port / joint".
CONTAIN_STROKE = "#9a9a9a"
CONNECT_STROKE = "#0d7a6f"

JOINT_WORDS = {
    "module_seat": "drops into",
    "pressure_hatch": "pressure hatch",
    "skin_cutout": "cut into skin",
    "fixed": "bolted to",
    "revolute": "hinged to",
    "duct": "duct to",
    "keel_mount": "keel-mounted aft of",
    "floor_mount": "bolted to floor of",
    "aligns_with": "aligns with",
    "umbilical": "umbilical to",
    "power_cable": "power cable",
    "alpha_path": "alphas to DEC",
    "rf_feed": "waveguides to",
    "waveguide": "waveguides to",
    "magnet_bus": "magnet leads to",
    "magnet_power": "powers",
    "coolant_loop": "coolant loop",
    "cryo_cool": "cools",
    "fuel_feed": "feed line",
    "solid_feed": "solid feed",
    "startup_power": "startup power",
    "rotation_drive": "rotation drive",
    "chamber_neck": "necks into",
}


def is_collection(node: dict) -> bool:
    """Organizational bag of parts — not a single physical item."""
    return node.get("kind") == "assembly" or node.get("collection") is True


def walk_containment(
    node: dict,
    lines: list[str],
    collections: list[str],
    parts: list[str],
    parent: str | None = None,
) -> int:
    """Append node defs + containment edges. Returns number of containment edges added."""
    nid = node["id"]
    label = node.get("label", nid).replace('"', "'")
    if is_collection(node):
        lines.append(f'  {nid}(["{label}"])')
        collections.append(nid)
    else:
        lines.append(f'  {nid}["{label}"]')
        parts.append(nid)
    n_edges = 0
    if parent:
        lines.append(f"  {parent} --> {nid}")
        n_edges = 1
    for ch in node.get("children", []):
        n_edges += walk_containment(ch, lines, collections, parts, nid)
    return n_edges


def main() -> None:
    asm = json.loads(ASM.read_text())
    lines: list[str] = [
        "%% Plain-English assembly from assembly.json",
        "%% Grey arrows = containment (A contains B).",
        "%% Teal arrows = physical connection / joint at a port.",
        "%% Dashed blue stadium = collection (organizational, not hardware).",
        "%% Regenerated by emit_assembly_mermaid.py",
        "flowchart TB",
        f"  linkStyle default stroke:{CONTAIN_STROKE},stroke-width:1.5px",
        "  classDef collection fill:#e7eef8,stroke:#5a6f8c,stroke-width:1.8px,stroke-dasharray:6 4,color:#243447",
        "  classDef part fill:#ffffff,stroke:#333,stroke-width:1.5px,color:#222",
    ]

    collections: list[str] = []
    parts: list[str] = []
    n_contain = walk_containment(asm["root"], lines, collections, parts)
    if collections:
        lines.append(f"  class {','.join(collections)} collection")
    if parts:
        lines.append(f"  class {','.join(parts)} part")

    lines.append("")
    lines.append("  %% Connections (ports / joints)")
    n_connect = 0
    seen: set[tuple] = set()
    for j in asm["joints"]:
        a = j["a"].split(".")[0]
        b = j["b"].split(".")[0]
        if a == b:
            continue
        key = (tuple(sorted([a, b])), j["type"])
        if key in seen:
            continue
        seen.add(key)
        words = JOINT_WORDS.get(j["type"], j["type"])
        # Thick arrow with label — styled teal below
        lines.append(f"  {a} ==>|{words}| {b}")
        n_connect += 1

    # linkStyle index = order of edges in the graph (containment first, then connections)
    if n_contain:
        contain_idx = ",".join(str(i) for i in range(n_contain))
        lines.append(
            f"  linkStyle {contain_idx} stroke:{CONTAIN_STROKE},stroke-width:1.5px,color:{CONTAIN_STROKE}"
        )
    if n_connect:
        connect_idx = ",".join(str(i) for i in range(n_contain, n_contain + n_connect))
        lines.append(
            f"  linkStyle {connect_idx} stroke:{CONNECT_STROKE},stroke-width:2.5px,color:{CONNECT_STROKE}"
        )

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT} ({n_contain} grey containment, {n_connect} teal connections)")


if __name__ == "__main__":
    main()
