#!/usr/bin/env python3
"""Emit plain-English Mermaid: grey containment, colored connection arrows.

Thin wrapper over `lib/mermaid_builder.py` (the same visible-set/edge-label
algorithm used by the interactive hierarchy app and by `emit_paper_mermaid.py`
for the arxiv.md figures). This script always fully expands the whole tree
(no hard scope, no boundary stubs, no sibling tinting) and keeps its own
historical joint-word wording, so `assembly_hierarchy.mmd` and the
interactive outliner are unaffected by the shared module's defaults.
"""

from __future__ import annotations

import sys
from pathlib import Path

CAD = Path(__file__).resolve().parent
sys.path.insert(0, str(CAD))

from lib.assembly_parser import load_assembly  # noqa: E402
from lib.mermaid_builder import build_mermaid  # noqa: E402

ASM = CAD / "assembly.json"
OUT = CAD / "assembly_hierarchy.mmd"

# Historical wording for this export specifically (predates the shared
# JOINT_WORDS in lib/mermaid_builder.py, which mirrors app.js instead).
JOINT_WORDS = {
    "module_seat": "drops into",
    "pressure_hatch": "pressure hatch",
    "skin_cutout": "cut into skin",
    "fixed": "bolted to",
    "revolute": "hinged to",
    "duct": "duct to",
    "keel_mount": "keel-mounted aft of",
    "floor_mount": "bolted to floor of",
    "aligns_with": "aligns with",
    "umbilical": "umbilical to",
    "power_cable": "power cable",
    "alpha_path": "alphas to DEC",
    "rf_feed": "waveguides to",
    "waveguide": "waveguides to",
    "magnet_bus": "magnet leads to",
    "magnet_power": "powers",
    "coolant_loop": "coolant loop",
    "cryo_cool": "cools",
    "fuel_feed": "feed line",
    "solid_feed": "solid feed",
    "startup_power": "startup power",
    "rotation_drive": "rotation drive",
    "chamber_neck": "necks into",
}


def all_ids_preorder(root: dict) -> list[str]:
    """Every node id, depth-first — i.e. the whole tree fully expanded."""
    ids: list[str] = []

    def walk(node: dict) -> None:
        ids.append(node["id"])
        for ch in node.get("children") or []:
            walk(ch)

    walk(root)
    return ids


def main() -> None:
    asm = load_assembly(ASM)
    visible = all_ids_preorder(asm["root"])

    result = build_mermaid(
        asm,
        visible,
        scope_root=None,
        use_tints=False,
        joint_words=JOINT_WORDS,
    )

    header = [
        "%% Plain-English assembly from assembly.json",
        "%% Grey arrows = containment (A contains B).",
        "%% Teal arrows = physical connection / joint at a port.",
        "%% Dashed blue stadium = collection (organizational, not hardware).",
        "%% Regenerated by emit_assembly_mermaid.py (via lib/mermaid_builder.py)",
    ]
    OUT.write_text("\n".join(header) + "\n" + result["src"] + "\n")
    print(f"Wrote {OUT} ({result['n_contain']} grey containment, {result['n_connect']} teal connections)")


if __name__ == "__main__":
    main()
