#!/usr/bin/env python3
"""Generate FlightGear ``sound.xml`` from ``orbitron_sound_assets.yaml``.

Each sound entry may include ``flightgear:`` (fx tag, volumes, pitch, positions).
``part_mesh`` is echoed in XML comments so acoustic sources stay traceable to CAD.
"""
from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Mapping

import yaml

from orbitron_aircraft_pkg import aircraft_package_dir


def _text(parent: ET.Element, tag: str, value: str | float | int) -> None:
    el = ET.SubElement(parent, tag)
    el.text = str(value)


def _binding_block(parent: ET.Element, tag: str, mapping: Mapping[str, Any]) -> None:
    """Sub-element with numeric/string children (e.g. volume, pitch)."""
    el = ET.SubElement(parent, tag)
    for key in ("property", "factor", "offset", "min", "max"):
        if key in mapping and mapping[key] is not None:
            _text(el, key, mapping[key])


def _build_fx_child(
    fx: ET.Element,
    *,
    part_mesh: str,
    fg: Mapping[str, Any],
    file_basename: str,
) -> None:
    tag = str(fg["fx_tag"])
    node = ET.SubElement(fx, tag)
    node.append(ET.Comment(f" part_mesh={part_mesh} "))
    _text(node, "name", fg["display_name"])
    _text(node, "mode", fg["mode"])
    path = fg.get("path")
    if path is None:
        path = f"Sounds/{file_basename}"
    _text(node, "path", path)

    cond = fg.get("condition") or {}
    if cond.get("property"):
        c = ET.SubElement(node, "condition")
        _text(c, "property", cond["property"])

    vol = fg.get("volume")
    if isinstance(vol, dict):
        _binding_block(node, "volume", vol)

    pitch = fg.get("pitch")
    if isinstance(pitch, dict) and pitch:
        _binding_block(node, "pitch", pitch)

    pos = fg.get("position") or {}
    if pos:
        p = ET.SubElement(node, "position")
        for axis in ("x", "y", "z"):
            if axis in pos:
                _text(p, axis, pos[axis])

    if "reference_dist" in fg:
        _text(node, "reference-dist", fg["reference_dist"])
    if "max_dist" in fg:
        _text(node, "max-dist", fg["max_dist"])


def build_sound_xml_tree(spec: Mapping[str, Any]) -> ET.ElementTree:
    sounds = spec.get("sounds")
    if not isinstance(sounds, list):
        raise ValueError("spec must contain 'sounds' list")

    root_el = ET.Element("PropertyList")
    root_el.append(
        ET.Comment(
            "\n  Reactive soundscape: volumes from JSBSim orbitron_soundscape.\n"
            "  Generated by tools/compile_sound_xml_from_yaml.py — edit orbitron_sound_assets.yaml.\n"
        )
    )
    fx = ET.SubElement(root_el, "fx")

    for i, entry in enumerate(sounds):
        if not isinstance(entry, dict):
            raise TypeError(f"sounds[{i}] must be a mapping")
        fg = entry.get("flightgear")
        if not isinstance(fg, dict):
            raise ValueError(f"sounds[{i}] missing flightgear mapping")
        fname = entry.get("file")
        if not fname:
            raise ValueError(f"sounds[{i}] missing file")
        mesh = str(entry.get("part_mesh") or entry.get("mesh") or "unknown")
        _build_fx_child(fx, part_mesh=mesh, fg=fg, file_basename=str(fname))

    return ET.ElementTree(root_el)


def _indent(elem: ET.Element, level: int = 0) -> None:
    pad = "\n" + "    " * level
    pad_child = "\n" + "    " * (level + 1)
    children = list(elem)
    if children:
        if not elem.text or not elem.text.strip():
            elem.text = pad_child
        for child in children:
            _indent(child, level + 1)
        if not elem.tail or not elem.tail.strip():
            elem.tail = pad
    else:
        if level and (not elem.tail or not elem.tail.strip()):
            elem.tail = pad
    for j, child in enumerate(children):
        if j + 1 < len(children):
            nxt = children[j + 1]
            if child.tail is None or not str(child.tail).strip():
                child.tail = pad_child
        else:
            if child.tail is None or not str(child.tail).strip():
                child.tail = pad


def render_sound_xml(spec_path: Path) -> str:
    data = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("YAML root must be a mapping")
    tree = build_sound_xml_tree(data)
    root = tree.getroot()
    assert root is not None
    _indent(root, 0)
    root.tail = "\n"
    return '<?xml version="1.0"?>\n' + ET.tostring(root, encoding="unicode")


def _default_sound_xml_path(spec_path: Path) -> Path:
    """``<repo>/Aircraft/<aircraft.package_dir>/Sounds/sound.xml`` for the standard spec layout."""
    spec_path = spec_path.resolve()
    parents = spec_path.parents
    if len(parents) < 4:
        raise ValueError(f"spec path too shallow for default output: {spec_path}")
    repo_root = parents[3]
    expected_asm = (repo_root / "ssto" / "orbitron" / "assembly_specs").resolve()
    if spec_path.parent.resolve() != expected_asm:
        raise ValueError(
            "default --out only applies when --spec is under "
            f"{expected_asm} (got {spec_path}); pass --out explicitly"
        )
    pkg = aircraft_package_dir(repo_root)
    return (repo_root / "Aircraft" / pkg / "Sounds" / "sound.xml").resolve()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", type=Path, required=True, help="orbitron_sound_assets.yaml")
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output sound.xml (default: Aircraft/<aircraft.package_dir>/Sounds/sound.xml under repo root)",
    )
    args = ap.parse_args()
    spec = args.spec.resolve()
    if not spec.is_file():
        print(f"error: spec not found: {spec}", file=sys.stderr)
        return 1
    out = args.out
    if out is None:
        out = _default_sound_xml_path(spec)
    out = out.resolve()
    text = render_sound_xml(spec)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print("Wrote", out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
