#!/usr/bin/env python3
"""Emit Mermaid from orbitron.ac: physical AC3D tree and optional logical assemblies.

Physical tree: OBJECT / kids under world. Logical tree: nested subgraphs from
``orbitron_lab.yaml`` (``logical.groups``) or a legacy logical-only YAML / JSON.
Mesh names must match orbitron.ac.
"""
from __future__ import annotations

import argparse
import html
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from orbitron_aircraft_pkg import aircraft_package_dir
from orbitron_logical_assemblies_spec import load_logical_assemblies_spec

_REPO_ROOT = Path(__file__).resolve().parents[1]
_ORBITRON_PKG = aircraft_package_dir(_REPO_ROOT)
_DEFAULT_ASSEMBLIES_SPEC = _REPO_ROOT / "ssto" / "orbitron" / "assembly_specs" / "orbitron_lab.yaml"
_DEFAULT_ORBITRON_AC = _REPO_ROOT / "Aircraft" / _ORBITRON_PKG / "Models" / "orbitron.ac"
_DEFAULT_PARTS_MMD = (
    _REPO_ROOT / "Aircraft" / _ORBITRON_PKG / "build" / "orbitron_ac_parts_hierarchy.mmd"
)


@dataclass
class ACNode:
    otype: str
    name: str
    children: list[ACNode] = field(default_factory=list)


def _parse_name_line(line: str) -> str | None:
    m = re.match(r'name "([^"]*)"', line)
    return m.group(1) if m else None


def read_ac_object(lines: list[str], start: int) -> tuple[ACNode, int]:
    if start >= len(lines) or not lines[start].startswith("OBJECT "):
        raise ValueError(f"Expected OBJECT at line {start + 1}, got {lines[start]!r}")

    otype = lines[start].split(None, 1)[1].strip()
    i = start + 1
    name = "(unnamed)"
    if i < len(lines) and lines[i].startswith("name "):
        parsed = _parse_name_line(lines[i])
        if parsed is not None:
            name = parsed
        i += 1

    kids = 0
    while i < len(lines):
        if lines[i].startswith("kids "):
            kids = int(lines[i].split()[1])
            i += 1
            break
        i += 1

    children: list[ACNode] = []
    for _ in range(kids):
        child, i = read_ac_object(lines, i)
        children.append(child)

    return ACNode(otype=otype, name=name, children=children), i


def find_first_object_line(lines: list[str]) -> int:
    for idx, line in enumerate(lines):
        if line.startswith("OBJECT "):
            return idx
    raise ValueError("No OBJECT record found (not a valid AC3D file?)")


def parse_ac(path: Path) -> ACNode:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    root_at = find_first_object_line(lines)
    root, pos = read_ac_object(lines, root_at)
    if pos < len(lines):
        tail = lines[pos].strip()
        if tail.startswith("OBJECT"):
            sys.stderr.write(
                f"warning: trailing content after root tree at line {pos + 1}: {tail[:60]!r}\n"
            )
    return root


def collect_nodes_depth_first(root: ACNode) -> list[tuple[ACNode, ACNode | None]]:
    out: list[tuple[ACNode, ACNode | None]] = []

    def walk(n: ACNode, parent: ACNode | None) -> None:
        out.append((n, parent))
        for c in n.children:
            walk(c, n)

    walk(root, None)
    return out


def mermaid_escape_label(s: str) -> str:
    return s.replace('"', "#quot;")


def subgraph_title_html(title: str) -> str:
    """Bold subgraph title; escape for safe use inside Mermaid/HTML label."""
    return f"<b>{html.escape(title, quote=True)}</b>"


# Alternating fill by nesting depth (odd = warm, even = cool) for subgraph containers.
_SUBGRAPH_FILL_ODD = "#FFF8E1"
_SUBGRAPH_FILL_EVEN = "#E3F2FD"
_SUBGRAPH_STROKE_ODD = "#6D4C41"
_SUBGRAPH_STROKE_EVEN = "#1565C0"


def emit_mermaid_physical(root: ACNode, ac_path: Path, xml_note: str | None) -> str:
    rows: list[str] = []
    rows.append("%% Auto-generated by tools/orbitron_ac_hierarchy_mmd.py")
    rows.append(f'%% Source mesh: {ac_path.as_posix()}')
    rows.append("%% Physical AC3D OBJECT / kids tree (flat if Blender exported siblings only)")
    if xml_note:
        for line in xml_note.splitlines():
            rows.append(f"%% {line}")
    rows.append("flowchart TB")
    rows.append("  %% Same object names FlightGear uses for object-name picks")

    nodes_df = collect_nodes_depth_first(root)
    ids: dict[int, str] = {}
    for i, (node, _) in enumerate(nodes_df):
        ids[id(node)] = f"n{i}"

    for i, (node, _) in enumerate(nodes_df):
        nid = ids[id(node)]
        label = mermaid_escape_label(node.name)
        if node.otype and node.otype != "world":
            label = f"{label}<br/><small>{mermaid_escape_label(node.otype)}</small>"
        elif node.otype == "world":
            label = f"{label}<br/><small>world</small>"
        rows.append(f'  {nid}["{label}"]')

    for node, parent in nodes_df:
        if parent is None:
            continue
        rows.append(f"  {ids[id(parent)]} --> {ids[id(node)]}")

    return "\n".join(rows) + "\n"


def subgraph_id(key: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", key)
    if not s:
        s = "group"
    return "g_" + s


def part_node_id(mesh_name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", mesh_name)
    if not s:
        s = "part"
    return "p_" + s


def logical_node_id(group_key: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", group_key)
    if not s:
        s = "logical"
    return "log_" + s


_BLENDER_DUP_SUFFIX = re.compile(r"^(?P<base>.+)\.\d{3}$")


def _blender_duplicate_base(mesh_name: str) -> str | None:
    """Blender renames duplicate imports as ``Name.001`` — alias to canonical AC name."""
    m = _BLENDER_DUP_SUFFIX.match(mesh_name)
    return m.group("base") if m else None


def _meshes_covered_by_assemblies(mesh_names: set[str], part_to_group: dict[str, str]) -> set[str]:
    covered = set(part_to_group)
    for name in mesh_names:
        base = _blender_duplicate_base(name)
        if base is not None and base in part_to_group:
            covered.add(name)
    return covered


def _is_fg_runtime_panel_mesh(name: str) -> bool:
    """Meshes merged into orbitron.ac by build_orbitron_shuttle_panel_ac.py (not CadQuery lab)."""
    return (
        name.startswith("Panel_Switch_")
        or name.startswith("Panel_Guard_")
        or name.startswith("Panel_Lever_")
    )


def mesh_parts_list(spec: dict[str, Any]) -> list[str]:
    """Mesh objects declared on this group (synonym keys: mesh_parts, parts)."""
    mp = spec.get("mesh_parts")
    if mp is not None:
        if not isinstance(mp, list):
            raise ValueError("mesh_parts must be a list")
        return [str(x) for x in mp]
    p = spec.get("parts", [])
    if not isinstance(p, list):
        raise ValueError("parts must be a list")
    return [str(x) for x in p]


def load_assemblies_json(path: Path) -> dict[str, Any]:
    return load_logical_assemblies_spec(path)


def _logical_only_keys(groups: dict[str, Any]) -> set[str]:
    return {k for k, v in groups.items() if isinstance(v, dict) and v.get("logical_only")}


def validate_assemblies(mesh_names: set[str], data: dict[str, Any]) -> None:
    root_key = str(data["root"])
    groups: dict[str, Any] = data["groups"]
    if root_key not in groups:
        raise ValueError(f"root group {root_key!r} not found in groups")

    for key, spec in groups.items():
        if not isinstance(spec, dict):
            raise ValueError(f"group {key!r} must be an object")
        if "title" not in spec or not isinstance(spec["title"], str):
            raise ValueError(f"group {key!r} needs a string 'title'")
        for m in spec.get("members", []):
            if m not in groups:
                raise ValueError(f"group {key!r} references unknown member {m!r}")
        for p in mesh_parts_list(spec):
            if not isinstance(p, str):
                raise ValueError(f"group {key!r} has non-string mesh part name")
        if spec.get("logical_only"):
            if spec.get("mesh_parts") is not None or spec.get("parts"):
                raise ValueError(
                    f"logical_only group {key!r} must not declare mesh parts/parts"
                )
            if spec.get("members"):
                raise ValueError(
                    f"logical_only group {key!r} must not have members (use a composite parent)"
                )

    part_to_group: dict[str, str] = {}

    def visit(key: str, stack: set[str]) -> None:
        if key in stack:
            raise ValueError(f"cycle in assembly members involving {key!r}")
        stack.add(key)
        spec = groups[key]
        if spec.get("logical_only"):
            stack.remove(key)
            return
        for m in spec.get("members", []):
            visit(m, stack)
        for p in mesh_parts_list(spec):
            if p in part_to_group:
                raise ValueError(
                    f"mesh object {p!r} listed in both {part_to_group[p]!r} and {key!r}"
                )
            part_to_group[p] = key
        stack.remove(key)

    visit(root_key, set())

    runtime_panel = {n for n in mesh_names if _is_fg_runtime_panel_mesh(n)}
    covered = _meshes_covered_by_assemblies(mesh_names, part_to_group)
    missing = sorted(mesh_names - covered - runtime_panel)
    extra = sorted(set(part_to_group) - mesh_names)
    if missing:
        raise ValueError(
            "assemblies spec does not cover all mesh objects: "
            + ", ".join(missing)
        )
    if extra:
        raise ValueError(
            "assemblies spec references unknown mesh names: " + ", ".join(extra)
        )

    logical_keys = _logical_only_keys(groups)
    for i, conn in enumerate(data.get("connections", [])):
        if not isinstance(conn, dict):
            raise ValueError(f"connections[{i}] must be an object")
        a = conn.get("from")
        b = conn.get("to")
        if not isinstance(a, str) or not isinstance(b, str):
            raise ValueError(f"connections[{i}] needs string from and to")
        for end in (a, b):
            if end not in mesh_names and end not in logical_keys:
                raise ValueError(
                    f"connections[{i}] endpoint {end!r} is not a mesh name "
                    "or a logical_only group key"
                )
        k = conn.get("kind", "solid")
        if k not in ("solid", "dotted"):
            raise ValueError(f"connections[{i}] kind must be 'solid' or 'dotted'")

    _emit_glossary_lines(data)


def _emit_glossary_lines(data: dict[str, Any]) -> list[str]:
    out: list[str] = []
    glossary = data.get("glossary")
    if not glossary:
        return out
    if not isinstance(glossary, list):
        raise ValueError("'glossary' must be a list")
    out.append("%% --- Glossary (engineering terms used in the diagram) ---")
    for i, entry in enumerate(glossary):
        if not isinstance(entry, dict):
            raise ValueError(f"glossary[{i}] must be an object")
        term = entry.get("term", "")
        defin = entry.get("definition", "")
        if not isinstance(term, str) or not isinstance(defin, str):
            raise ValueError(f"glossary[{i}] needs string term and definition")
        line = f"{term}: {defin}"
        max_chunk = 96
        prefix = "%% "
        while line:
            chunk = line[:max_chunk]
            out.append(prefix + chunk)
            line = line[max_chunk:]
    out.append("%% --- End glossary ---")
    return out


def _resolve_connection_endpoint(
    name: str, mesh_names: set[str], logical_keys: set[str]
) -> str:
    if name in mesh_names:
        return part_node_id(name)
    if name in logical_keys:
        return logical_node_id(name)
    raise ValueError(f"unknown connection endpoint {name!r}")


def _mermaid_link_label_text(label: str) -> str:
    """Quote edge labels so /, |, (), etc. do not break the flowchart lexer."""
    inner = label.replace("\\", "\\\\").replace('"', "'")
    return f'"{inner}"'


def _emit_connection_line(
    conn: dict[str, Any], ac_mesh_names: set[str], logical_keys: set[str]
) -> str:
    a = _resolve_connection_endpoint(str(conn["from"]), ac_mesh_names, logical_keys)
    b = _resolve_connection_endpoint(str(conn["to"]), ac_mesh_names, logical_keys)
    kind = conn.get("kind", "solid")
    label = conn.get("label", "")
    if not isinstance(label, str):
        raise ValueError("connection label must be a string")
    if label:
        quoted = _mermaid_link_label_text(label)
        if kind == "dotted":
            return f"  {a} -.->|{quoted}| {b}"
        return f"  {a} -->|{quoted}| {b}"
    if kind == "dotted":
        return f"  {a} -.-> {b}"
    return f"  {a} --> {b}"


def emit_logical_mermaid(
    data: dict[str, Any],
    ac_path: Path,
    assemblies_json: Path,
    xml_note: str | None,
    ac_mesh_names: set[str],
) -> str:
    root_key = str(data["root"])
    groups: dict[str, Any] = data["groups"]
    lines: list[str] = []
    lines.append("%% Auto-generated by tools/orbitron_ac_hierarchy_mmd.py (logical view)")
    lines.append(f'%% Source mesh: {ac_path.as_posix()}')
    lines.append(f'%% Assembly map: {assemblies_json.as_posix()}')
    lines.append(
        "%% Nesting is engineering grouping; dashed edges are schematic / not separate AC objects."
    )
    if xml_note:
        for row in xml_note.splitlines():
            lines.append(f"%% {row}")
    lines.extend(_emit_glossary_lines(data))
    lines.append("flowchart TB")

    subgraph_style_queue: list[tuple[str, int]] = []
    mesh_part_ids: list[str] = []
    logical_node_ids: list[str] = []

    def render_group(key: str, depth: int) -> None:
        pad = "  " * depth
        spec = groups[key]
        gid = subgraph_id(key)
        subgraph_style_queue.append((gid, depth))
        title = subgraph_title_html(str(spec["title"]))

        if spec.get("logical_only"):
            lines.append(f'{pad}subgraph {gid}["{title}"]')
            if depth == 1:
                lines.append(f"{pad}  direction TB")
            nid = logical_node_id(key)
            logical_node_ids.append(nid)
            detail = str(spec.get("detail", ""))
            inner_title = html.escape(str(spec["title"]), quote=True)
            if detail:
                inner = (
                    f"<b>{inner_title}</b><br/><small>{html.escape(detail, quote=True)}</small>"
                )
            else:
                inner = f"<b>{inner_title}</b>"
            lines.append(f'{pad}  {nid}["{inner}"]')
            lines.append(f"{pad}end")
            return

        lines.append(f'{pad}subgraph {gid}["{title}"]')
        if depth == 1:
            lines.append(f"{pad}  direction TB")
        mp = mesh_parts_list(spec)
        for pname in mp:
            pid = part_node_id(str(pname))
            mesh_part_ids.append(pid)
            plab = mermaid_escape_label(str(pname))
            lines.append(f'{pad}  {pid}["{plab}<br/><small>mesh</small>"]')
        for mk in spec.get("members", []):
            render_group(str(mk), depth + 1)
        lines.append(f"{pad}end")

    render_group(root_key, 1)

    logical_keys = _logical_only_keys(groups)
    for conn in data.get("connections", []):
        if isinstance(conn, dict):
            lines.append(_emit_connection_line(conn, ac_mesh_names, logical_keys))

    for gid, depth in subgraph_style_queue:
        fill = _SUBGRAPH_FILL_ODD if depth % 2 == 1 else _SUBGRAPH_FILL_EVEN
        stroke = _SUBGRAPH_STROKE_ODD if depth % 2 == 1 else _SUBGRAPH_STROKE_EVEN
        lines.append(
            f"  style {gid} fill:{fill},stroke:{stroke},stroke-width:2px,color:#1a1a1a"
        )

    if mesh_part_ids:
        lines.append(
            "  classDef meshNode fill:#EDE7F6,stroke:#5E35B1,stroke-width:1px,color:#222"
        )
        chunk = 12
        for i in range(0, len(mesh_part_ids), chunk):
            batch = ",".join(mesh_part_ids[i : i + chunk])
            lines.append(f"  class {batch} meshNode")

    if logical_node_ids:
        lines.append(
            "  classDef logicalNode fill:#E8F5E9,stroke:#2E7D32,stroke-width:1px,color:#1b5e20"
        )
        ch = 14
        for i in range(0, len(logical_node_ids), ch):
            batch = ",".join(logical_node_ids[i : i + ch])
            lines.append(f"  class {batch} logicalNode")

    return "\n".join(lines) + "\n"


def orbitron_xml_offsets_note(xml_path: Path | None) -> str | None:
    if xml_path is None or not xml_path.is_file():
        return None
    tree = ET.parse(xml_path)
    root = tree.getroot()
    path_el = root.find("path")
    mesh = path_el.text.strip() if path_el is not None and path_el.text else ""
    off = root.find("offsets")

    def _off(tag: str) -> str:
        if off is None:
            return ""
        el = off.find(tag)
        return el.text.strip() if el is not None and el.text else ""

    pitch_v = _off("pitch-deg")
    roll_v = _off("roll-deg")
    head_v = _off("heading-deg")
    xv = _off("x-m")
    yv = _off("y-m")
    zv = _off("z-m")
    note_lines = [
        f"Orbitron.xml mesh: {mesh}",
        f"offsets: pitch-deg={pitch_v!s} roll-deg={roll_v!s} heading-deg={head_v!s} "
        f"x-m={xv!s} y-m={yv!s} z-m={zv!s}",
    ]
    return "\n".join(note_lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="AC3D parts tree → Mermaid flowchart(s)")
    ap.add_argument(
        "--ac",
        type=Path,
        default=_DEFAULT_ORBITRON_AC,
        help="Path to orbitron.ac",
    )
    ap.add_argument(
        "--orbitron-xml",
        type=Path,
        default=None,
        help="Optional Orbitron.xml for offset annotations in header comments",
    )
    ap.add_argument(
        "-o",
        "--out",
        type=Path,
        default=_DEFAULT_PARTS_MMD,
        help="Output for physical AC tree (.mmd)",
    )
    ap.add_argument(
        "--assemblies-spec",
        "--assemblies-json",
        dest="assemblies_spec",
        type=Path,
        default=_DEFAULT_ASSEMBLIES_SPEC,
        help="orbitron_lab.yaml (schema v2) or legacy logical-only .yaml / .json",
    )
    ap.add_argument(
        "--logical-out",
        type=Path,
        default=None,
        help="Optional second .mmd for logical assembly diagram",
    )
    args = ap.parse_args()

    ac_path = args.ac.resolve()
    if not ac_path.is_file():
        print(f"error: AC file not found: {ac_path}", file=sys.stderr)
        return 1

    xml_path = args.orbitron_xml
    if xml_path is not None:
        xml_path = xml_path.resolve()
    else:
        guess = ac_path.parent / "Orbitron.xml"
        if guess.is_file():
            xml_path = guess

    root = parse_ac(ac_path)
    note = orbitron_xml_offsets_note(xml_path)
    physical = emit_mermaid_physical(root, ac_path, note)
    out_path = args.out.resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(physical, encoding="utf-8")
    print(f"Wrote {out_path} ({len(root.children)} top-level objects under world)")

    logical_out = args.logical_out
    if logical_out is not None:
        aj = args.assemblies_spec
        aj = aj.resolve()
        if not aj.is_file():
            print(f"error: assemblies spec not found: {aj}", file=sys.stderr)
            return 1
        mesh_names = {c.name for c in root.children}
        try:
            data = load_assemblies_json(aj)
            validate_assemblies(mesh_names, data)
        except (ValueError, yaml.YAMLError) as e:
            print(f"error: {e}", file=sys.stderr)
            return 1
        logical = emit_logical_mermaid(data, ac_path, aj, note, mesh_names)
        logical_path = logical_out.resolve()
        logical_path.parent.mkdir(parents=True, exist_ok=True)
        logical_path.write_text(logical, encoding="utf-8")
        print(f"Wrote {logical_path} (logical assemblies)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
