-- Normalized catalog for the p–¹¹B SoA survey (pb11_fusion_soa_2026/arxiv.md)
-- Regenerated by scripts/build_catalog_db.py

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Static scoring / taxonomy
-- ---------------------------------------------------------------------------

CREATE TABLE score_level (
    code TEXT PRIMARY KEY,              -- full | partial | weak | na
    symbol TEXT NOT NULL UNIQUE,        -- ● | ◐ | ○ | —
    numeric_value INTEGER,              -- 2 | 1 | 0 | NULL
    label TEXT NOT NULL,
    description TEXT
);

CREATE TABLE diligence_gate (
    code TEXT PRIMARY KEY,              -- F K R A L C M B T S H
    name TEXT NOT NULL,
    question TEXT NOT NULL,
    sort_order INTEGER NOT NULL UNIQUE,
    used_in_pos INTEGER NOT NULL DEFAULT 1  -- 0 for C (label only) and B
);

CREATE TABLE scoring_metric (
    code TEXT PRIMARY KEY,              -- POS | POS_STAR
    name TEXT NOT NULL,
    formula TEXT NOT NULL,
    denominator REAL,
    description TEXT NOT NULL
);

CREATE TABLE scoring_metric_weight (
    metric_code TEXT NOT NULL REFERENCES scoring_metric(code),
    gate_code TEXT NOT NULL REFERENCES diligence_gate(code),
    weight REAL NOT NULL,
    PRIMARY KEY (metric_code, gate_code)
);

CREATE TABLE kappa_factor (
    kappa REAL PRIMARY KEY,
    when_used TEXT NOT NULL
);

CREATE TABLE matrix_axis (
    code TEXT PRIMARY KEY,              -- time | confinement | fuel | kinetics
    name TEXT NOT NULL,
    plain_question TEXT NOT NULL,
    typical_answers TEXT NOT NULL,
    sort_order INTEGER NOT NULL UNIQUE
);

CREATE TABLE time_mode (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE confinement_family (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    short_name TEXT,
    description TEXT
);

CREATE TABLE fuel_end_state (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    is_p11b_clean INTEGER NOT NULL DEFAULT 0,
    description TEXT
);

CREATE TABLE kinetics_regime (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE path_type (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE entity_kind (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE  -- person | company | university | lab | consortium | government | facility | other_org
);

CREATE TABLE prototype_kind (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE  -- machine | digital_twin | concept | facility | lab_campaign | imputed_theory
);

CREATE TABLE document_table (
    table_id TEXT PRIMARY KEY,          -- e.g. tab:scorecard
    title TEXT NOT NULL,
    section TEXT
);

-- ---------------------------------------------------------------------------
-- Entities (people + organizational)
-- ---------------------------------------------------------------------------

CREATE TABLE entity (
    id INTEGER PRIMARY KEY,
    canonical_name TEXT NOT NULL UNIQUE,
    kind_id INTEGER NOT NULL REFERENCES entity_kind(id),
    short_name TEXT,
    country TEXT,
    website TEXT,
    notes TEXT
);

CREATE TABLE entity_alias (
    id INTEGER PRIMARY KEY,
    entity_id INTEGER NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    alias TEXT NOT NULL UNIQUE
);

CREATE INDEX idx_entity_kind ON entity(kind_id);

-- ---------------------------------------------------------------------------
-- Architectures / projects (catalog paths)
-- ---------------------------------------------------------------------------

CREATE TABLE architecture (
    id INTEGER PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    path_type_id INTEGER REFERENCES path_type(id),
    time_mode_id INTEGER REFERENCES time_mode(id),
    confinement_family_id INTEGER REFERENCES confinement_family(id),
    fuel_end_state_id INTEGER REFERENCES fuel_end_state(id),
    kinetics_regime_id INTEGER REFERENCES kinetics_regime(id),
    catalog_status TEXT,
    notes TEXT,
    source_section TEXT,
    in_scorecard INTEGER NOT NULL DEFAULT 0,
    in_plant_odds INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE architecture_entity (
    architecture_id INTEGER NOT NULL REFERENCES architecture(id) ON DELETE CASCADE,
    entity_id INTEGER NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    role TEXT NOT NULL,  -- lead | collaborator | spinout_of | host | program
    PRIMARY KEY (architecture_id, entity_id, role)
);

-- Physical / I/O design envelope (survey-informed editorial theater values)
CREATE TABLE plant_spec (
    architecture_id INTEGER PRIMARY KEY REFERENCES architecture(id) ON DELETE CASCADE,
    footprint_m2 REAL,                 -- hall / pad footprint
    vessel_length_m REAL,
    vessel_diameter_m REAL,
    rated_gross_MW REAL,               -- intended gross electric generation
    rated_net_MW REAL,                 -- intended busbar export
    rated_driver_MW REAL,              -- wall-plug driver / recirculating class
    starter_battery_kWh REAL NOT NULL, -- site startup bank (fully charged at RUN)
    starter_battery_V REAL NOT NULL,   -- DC bus nominal
    design_fuel_H_mg_s REAL,           -- design proton/H feed
    design_fuel_B11_mg_s REAL,         -- design boron-11 feed
    neutron_energy_fraction REAL,      -- ~0 for clean p11B; higher for D–T learning
    -- Honest black-start / first-production window (not full driver on battery)
    time_to_production_s REAL NOT NULL DEFAULT 0,  -- 0 = instantaneous production model
    startup_aux_MW REAL NOT NULL DEFAULT 0,        -- continuous house/aux during prep
    startup_energy_kWh REAL NOT NULL DEFAULT 0,    -- one-shot magnet/bank energy over prep
    startup_notes TEXT,                -- justification for the three fields above
    notes TEXT,
    data_quality TEXT NOT NULL DEFAULT 'editorial'  -- survey | editorial | aspirational
);

-- ---------------------------------------------------------------------------
-- Prototypes (machines, facilities, digital twins, concepts)
-- ---------------------------------------------------------------------------

CREATE TABLE prototype (
    id INTEGER PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    kind_id INTEGER NOT NULL REFERENCES prototype_kind(id),
    architecture_id INTEGER REFERENCES architecture(id),
    status TEXT,  -- operating | under_construction | planned | concept | product | retired
    description TEXT,
    notes TEXT
);

CREATE TABLE prototype_entity (
    prototype_id INTEGER NOT NULL REFERENCES prototype(id) ON DELETE CASCADE,
    entity_id INTEGER NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    role TEXT NOT NULL,  -- owner | operator | developer | host_facility | collaborator
    PRIMARY KEY (prototype_id, entity_id, role)
);

CREATE INDEX idx_prototype_architecture ON prototype(architecture_id);
CREATE INDEX idx_prototype_kind ON prototype(kind_id);

-- ---------------------------------------------------------------------------
-- Diligence gate scores + plant odds
-- ---------------------------------------------------------------------------

CREATE TABLE architecture_gate_score (
    architecture_id INTEGER NOT NULL REFERENCES architecture(id) ON DELETE CASCADE,
    gate_code TEXT NOT NULL REFERENCES diligence_gate(code),
    score_code TEXT REFERENCES score_level(code),
    confinement_label TEXT,  -- Gate C named class when present
    notes TEXT,
    PRIMARY KEY (architecture_id, gate_code)
);

CREATE TABLE plant_odds (
    architecture_id INTEGER PRIMARY KEY REFERENCES architecture(id) ON DELETE CASCADE,
    rank INTEGER NOT NULL UNIQUE,
    pos REAL,
    kappa REAL NOT NULL REFERENCES kappa_factor(kappa),
    pos_star REAL NOT NULL,
    q_ge_1_window TEXT,
    prototype_window TEXT,
    grid_product_window TEXT,
    pos_approximate INTEGER NOT NULL DEFAULT 0,
    rationale TEXT
);

-- ---------------------------------------------------------------------------
-- Bibliographic references
-- ---------------------------------------------------------------------------

CREATE TABLE reference (
    id INTEGER PRIMARY KEY,             -- citation number from SoA survey
    year INTEGER,
    title TEXT,
    venue TEXT,
    doi TEXT,
    url TEXT,
    raw_text TEXT NOT NULL,
    is_patent INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE reference_author (
    reference_id INTEGER NOT NULL REFERENCES reference(id) ON DELETE CASCADE,
    entity_id INTEGER NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    author_position INTEGER NOT NULL,
    is_etal INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (reference_id, author_position)
);

CREATE TABLE reference_organization (
    reference_id INTEGER NOT NULL REFERENCES reference(id) ON DELETE CASCADE,
    entity_id INTEGER NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    role TEXT NOT NULL,  -- author_org | assignee | publisher | mentioned
    PRIMARY KEY (reference_id, entity_id, role)
);

CREATE TABLE architecture_reference (
    architecture_id INTEGER NOT NULL REFERENCES architecture(id) ON DELETE CASCADE,
    reference_id INTEGER NOT NULL REFERENCES reference(id) ON DELETE CASCADE,
    PRIMARY KEY (architecture_id, reference_id)
);

CREATE TABLE prototype_reference (
    prototype_id INTEGER NOT NULL REFERENCES prototype(id) ON DELETE CASCADE,
    reference_id INTEGER NOT NULL REFERENCES reference(id) ON DELETE CASCADE,
    PRIMARY KEY (prototype_id, reference_id)
);

-- ---------------------------------------------------------------------------
-- Other survey tables (normalized rows)
-- ---------------------------------------------------------------------------

CREATE TABLE aneutronic_channel (
    id INTEGER PRIMARY KEY,
    reaction TEXT NOT NULL UNIQUE,
    primary_products TEXT NOT NULL,
    q_value_mev REAL,
    thermal_ignition_vs_dt TEXT
);

CREATE TABLE sister_fuel_pursuit (
    id INTEGER PRIMARY KEY,
    entity_id INTEGER REFERENCES entity(id),
    architecture_id INTEGER REFERENCES architecture(id),
    fuel_claim TEXT,
    clean_vs_p11b TEXT,
    notes TEXT
);

CREATE TABLE hedp_degenerate_host (
    architecture_id INTEGER PRIMARY KEY REFERENCES architecture(id) ON DELETE CASCADE,
    why_helps TEXT NOT NULL
);

CREATE TABLE pppl_spinout (
    architecture_id INTEGER PRIMARY KEY REFERENCES architecture(id) ON DELETE CASCADE,
    fuel_machine TEXT,
    capital_signal TEXT,
    federal_milestone_signal TEXT,
    public_web_brand TEXT,
    outlook_2026_2030 TEXT
);

CREATE TABLE digital_twin_tool (
    prototype_id INTEGER PRIMARY KEY REFERENCES prototype(id) ON DELETE CASCADE,
    claim TEXT,
    license_openness TEXT,
    access_how TEXT,
    repo TEXT  -- public GitHub / GitLab / Docker Hub / etc. when redistributable
);

CREATE TABLE legal_footprint (
    entity_id INTEGER PRIMARY KEY REFERENCES entity(id) ON DELETE CASCADE,
    domain_status TEXT,
    corp_entity TEXT,
    uspto_trademark TEXT,
    notes TEXT
);

CREATE TABLE patent (
    id INTEGER PRIMARY KEY,
    number TEXT NOT NULL UNIQUE,
    title_short TEXT,
    entity_id INTEGER REFERENCES entity(id),
    assignee_notes TEXT,
    reference_id INTEGER REFERENCES reference(id)
);

CREATE TABLE patent_citation_edge (
    id INTEGER PRIMARY KEY,
    seed_patent_id INTEGER NOT NULL REFERENCES patent(id) ON DELETE CASCADE,
    direction TEXT NOT NULL CHECK (direction IN ('cited', 'citing')),
    related_patent_id INTEGER REFERENCES patent(id),
    related_description TEXT NOT NULL
);

CREATE TABLE mention (
    id INTEGER PRIMARY KEY,
    entity_id INTEGER NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    context TEXT NOT NULL,           -- where / how mentioned
    architecture_id INTEGER REFERENCES architecture(id),
    prototype_id INTEGER REFERENCES prototype(id),
    reference_id INTEGER REFERENCES reference(id)
);

CREATE INDEX idx_mention_entity ON mention(entity_id);
CREATE INDEX idx_reference_author_entity ON reference_author(entity_id);
CREATE INDEX idx_architecture_entity_entity ON architecture_entity(entity_id);

-- Convenience views ---------------------------------------------------------

CREATE VIEW v_scorecard AS
SELECT
    a.slug,
    a.name AS architecture,
    MAX(CASE WHEN ags.gate_code = 'C' THEN ags.confinement_label END) AS C,
    MAX(CASE WHEN ags.gate_code = 'F' THEN sl.symbol END) AS F,
    MAX(CASE WHEN ags.gate_code = 'K' THEN sl.symbol END) AS K,
    MAX(CASE WHEN ags.gate_code = 'R' THEN sl.symbol END) AS R,
    MAX(CASE WHEN ags.gate_code = 'A' THEN sl.symbol END) AS A,
    MAX(CASE WHEN ags.gate_code = 'L' THEN sl.symbol END) AS L,
    MAX(CASE WHEN ags.gate_code = 'M' THEN sl.symbol END) AS M,
    MAX(CASE WHEN ags.gate_code = 'T' THEN sl.symbol END) AS T,
    MAX(CASE WHEN ags.gate_code = 'S' THEN sl.symbol END) AS S,
    MAX(CASE WHEN ags.gate_code = 'H' THEN sl.symbol END) AS H
FROM architecture a
JOIN architecture_gate_score ags ON ags.architecture_id = a.id
LEFT JOIN score_level sl ON sl.code = ags.score_code
WHERE a.in_scorecard = 1 OR a.in_plant_odds = 1
GROUP BY a.id
ORDER BY a.name;

CREATE VIEW v_plant_odds AS
SELECT
    po.rank,
    a.slug,
    a.name AS path,
    pt.name AS path_type,
    po.pos,
    po.kappa,
    po.pos_star,
    po.q_ge_1_window,
    po.prototype_window,
    po.grid_product_window,
    po.pos_approximate,
    po.rationale
FROM plant_odds po
JOIN architecture a ON a.id = po.architecture_id
LEFT JOIN path_type pt ON pt.id = a.path_type_id
ORDER BY po.rank;

CREATE VIEW v_prototype_map AS
SELECT
    p.slug AS prototype_slug,
    p.name AS prototype,
    pk.name AS prototype_kind,
    p.status,
    a.slug AS architecture_slug,
    a.name AS architecture,
    e.canonical_name AS entity,
    pe.role
FROM prototype p
JOIN prototype_kind pk ON pk.id = p.kind_id
LEFT JOIN architecture a ON a.id = p.architecture_id
LEFT JOIN prototype_entity pe ON pe.prototype_id = p.id
LEFT JOIN entity e ON e.id = pe.entity_id
ORDER BY pk.name, p.name, pe.role;

CREATE VIEW v_reference_authors AS
SELECT
    r.id AS reference_id,
    r.year,
    r.title,
    ra.author_position,
    e.canonical_name AS author,
    ek.name AS author_kind,
    ra.is_etal
FROM reference r
JOIN reference_author ra ON ra.reference_id = r.id
JOIN entity e ON e.id = ra.entity_id
JOIN entity_kind ek ON ek.id = e.kind_id
ORDER BY r.id, ra.author_position;
